default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("POSTGRES_HOST") { "db" } %>
  port: 5432
  username: <%= ENV.fetch("POSTGRES_USER") { "postgres" } %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") { "dream_journal_development" } %>

  
test:
  <<: *default
  database: app_test



production:
  <<: *default
  database: <%= ENV["POSTGRES_DB"] %>
