
default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  port: 5432
  username: postgres
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: app_development

  
test:
  <<: *default
  database: app_test



production:
  <<: *default
  database: app_production
  username: postgres
  password: <%= ENV["APP_DATABASE_PASSWORD"] %>
