name: E2E Tests

on:
  pull_request:
    branches: [main]

  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        working-directory: ./frontend
        run: yarn install --frozen-lockfile

      - name: Install Playwright browsers
        working-directory: ./frontend
        run: npx playwright install --with-deps

      - name: Run E2E tests
        working-directory: ./frontend
        run: npx playwright test
        env:
          BASE_URL: http://localhost:3000
          # テスト実行時にバックエンドAPIのURLを渡す
          NEXT_PUBLIC_API_URL: http://localhost:3001
